import Foundation
import Supabase

// MARK: - DTO

struct JournalPhoto: Codable, Identifiable, Hashable {
    let id: String
    var tripId: String
    var imageUrl: String
    var caption: String
    var dayNumber: Int?
    var activityId: String?
    let uploadedAt: String

    enum CodingKeys: String, CodingKey {
        case id, caption
        case tripId     = "trip_id"
        case imageUrl   = "image_url"
        case dayNumber  = "day_number"
        case activityId = "activity_id"
        case uploadedAt = "uploaded_at"
    }
}

// MARK: - Service

@Observable
final class JournalService {
    var photos: [JournalPhoto] = []
    var isLoading = false
    var errorMessage: String?

    private let db      = SupabaseManager.shared.database
    private let storage = SupabaseManager.shared.storage

    // ── Fetch all photos for a trip ───────────────────────────────────────

    func fetchPhotos(tripId: String) async {
        await MainActor.run { isLoading = true; errorMessage = nil }
        do {
            let result: [JournalPhoto] = try await db
                .from(Table.journalPhotos)
                .select()
                .eq("trip_id", value: tripId)
                .order("uploaded_at")
                .execute()
                .value
            await MainActor.run { photos = result; isLoading = false }
        } catch {
            await MainActor.run { errorMessage = error.localizedDescription; isLoading = false }
        }
    }

    // ── Add a photo ───────────────────────────────────────────────────────

    func addPhoto(
        tripId: String,
        dayNumber: Int?,
        activityId: String?,
        imageData: Data,
        caption: String
    ) async throws -> JournalPhoto {
        // Use a local UUID only for the storage path; DB id is generated by Postgres.
        let fileId  = UUID().uuidString
        let path    = "trips/\(tripId)/journal/\(fileId).jpg"
        let now     = ISO8601DateFormatter().string(from: .now)

        let urlString: String
        if CloudflareR2Config.isConfigured {
            urlString = try await CloudflareR2Service.shared.uploadImage(
                imageData, path: path, contentType: "image/jpeg"
            )
        } else {
            try await storage.upload(
                path, data: imageData,
                options: .init(contentType: "image/jpeg", upsert: false)
            )
            urlString = try storage.getPublicURL(path: path).absoluteString
        }

        var payload: [String: AnyJSON] = [
            "trip_id":     .string(tripId),
            "image_url":   .string(urlString),
            "caption":     .string(caption),
            "uploaded_at": .string(now),
        ]
        if let day = dayNumber  { payload["day_number"]  = .double(Double(day)) }
        if let act = activityId { payload["activity_id"] = .string(act) }

        let inserted: JournalPhoto = try await db
            .from(Table.journalPhotos)
            .insert(payload)
            .select()
            .single()
            .execute()
            .value

        await MainActor.run { photos.append(inserted) }
        return inserted
    }

    // ── Update caption ────────────────────────────────────────────────────

    func updateCaption(photoId: String, caption: String) async throws {
        try await db.from(Table.journalPhotos)
            .update(["caption": AnyJSON.string(caption)])
            .eq("id", value: photoId)
            .execute()
        if let idx = photos.firstIndex(where: { $0.id == photoId }) {
            await MainActor.run { photos[idx].caption = caption }
        }
    }

    // ── Delete a photo ────────────────────────────────────────────────────

    func deletePhoto(_ photo: JournalPhoto) async throws {
        let path = "trips/\(photo.tripId)/journal/\(photo.id).jpg"
        if !CloudflareR2Config.isConfigured {
            try? await storage.remove(paths: [path])
        }
        try await db.from(Table.journalPhotos).delete().eq("id", value: photo.id).execute()
        await MainActor.run { photos.removeAll { $0.id == photo.id } }
    }
}
